In [1783]:
import pandas as pd

In [1784]:
import statsmodels.api as sm

In [1785]:
Thesis = pd.read_csv("C:/Users/Chika/Desktop/MY THESIS/Thesis proper/Thesis python.csv")

In [1786]:
Thesis.head(5)

,Year,Session Name,Match Method,Round,ID,Other ID,Role (1=Prop.),Proposer Demand,Response,Earnings,Cumulative Earnings,Offers to Responders,offer size category,Response(value),Gender,Y_2021,Y_2020,Y_201916
0,2021,frcc4,random,1,1,20,1,9,r,0,0,1,0-2,0,M,1,0,0
1,2021,frcc4,random,1,2,15,1,6,a,6,6,4,03-Apr,1,F,1,0,0
2,2021,frcc4,random,1,3,24,1,9,r,0,0,1,0-2,0,F,1,0,0
3,2021,frcc4,random,1,4,21,1,7,r,0,0,3,03-Apr,0,F,1,0,0
4,2021,frcc4,random,1,5,22,1,6,a,6,6,4,03-Apr,1,M,1,0,0

In [1787]:
#create a single binary variable for gender (0 for female, 1 for male)
Thesis['Gender'] = (Thesis['Gender'] == 'M').astype(int)

In [1788]:
Thesis.head(10)

,Year,Session Name,Match Method,Round,ID,Other ID,Role (1=Prop.),Proposer Demand,Response,Earnings,Cumulative Earnings,Offers to Responders,offer size category,Response(value),Gender,Y_2021,Y_2020,Y_201916
0,2021,frcc4,random,1,1,20,1,9,r,0,0,1,0-2,0,1,1,0,0
1,2021,frcc4,random,1,2,15,1,6,a,6,6,4,03-Apr,1,0,1,0,0
2,2021,frcc4,random,1,3,24,1,9,r,0,0,1,0-2,0,0,1,0,0
3,2021,frcc4,random,1,4,21,1,7,r,0,0,3,03-Apr,0,0,1,0,0
4,2021,frcc4,random,1,5,22,1,6,a,6,6,4,03-Apr,1,1,1,0,0
5,2021,frcc4,random,1,6,23,1,5,a,5,5,5,05-Jun,1,0,1,0,0
6,2021,frcc4,random,1,7,19,1,5,a,5,5,5,05-Jun,1,1,1,0,0
7,2021,frcc4,random,1,8,14,1,6,a,6,6,4,03-Apr,1,0,1,0,0
8,2021,frcc4,random,1,9,18,1,5,a,5,5,5,05-Jun,1,1,1,0,0
9,2021,frcc4,random,1,10,16,1,5,a,5,5,5,05-Jun,1,0,1,0,0

In [1789]:
results = {}

In [1790]:
for rnd in range (1, 11):
    round_info = Thesis[Thesis['Round'] == 5]

In [1791]:
y = round_info['Response(value)']

In [1792]:
x = round_info[['Offers to Responders','Y_2021', 'Y_2020', 'Y_201916', 'Gender']]

In [1793]:
x = sm.add_constant(x)

In [1794]:
#perform the probit regression

In [1795]:
model = sm.Probit(y,x)

In [1796]:
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.317263
         Iterations 8

In [1797]:
#store the result of the model

In [1798]:
results[rnd] = result.summary()

In [1799]:
#Printing results for each round

In [1800]:
for rnd in range (1,11):
    print(f"Round{5} Results:\n")

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

Round5 Results:

In [1801]:
print("\n")

In [1802]:
round_info = Thesis[Thesis['Round'] == 10]

In [1803]:
x = round_info[['Offers to Responders', 'Y_2021', 'Y_2020', 'Y_201916', 'Gender']]

In [1804]:
x = sm.add_constant(x)

In [1805]:
y = round_info['Response(value)']

In [1806]:
ols_model = sm.OLS(y,x).fit()

In [1807]:
print(ols_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Response(value)   R-squared:                       0.048
Model:                            OLS   Adj. R-squared:                 -0.023
Method:                 Least Squares   F-statistic:                    0.6779
Date:                Wed, 26 Jun 2024   Prob (F-statistic):              0.516
Time:                        01:08:19   Log-Likelihood:                -9.4632
No. Observations:                  30   AIC:                             24.93
Df Residuals:                      27   BIC:                             29.13
Df Model:                           2
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Offers to Responders     0.0745      0.102      0.730      0.472      -0.135       0.284
Y_2021                5.271e-17   4.61e-17      1.144      0.263   -4.19e-17    1.47e-16
Y_2020                        0          0        nan        nan           0           0
Y_201916                 0.5426      0.380      1.428      0.165      -0.237       1.322
Gender                   0.0881      0.134      0.660      0.515      -0.186       0.362
==============================================================================
Omnibus:                       20.622   Durbin-Watson:                   2.164
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               25.433
Skew:                          -1.962   Prob(JB):                     3.00e-06
Kurtosis:                       5.224   Cond. No.                     1.66e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.74e-34. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [1808]:
P = 10

In [1809]:
def calculate_alpha(row):
    if row['Response'] == 'r':
        return(P-row['Offers to Responders']) / row['Offers to Responders']
    else:
        return 0.5

In [1810]:
Thesis['Alpha']= Thesis.apply(calculate_alpha, axis=1)

ZeroDivisionError: division by zero